from pathlib import Path

p = Path('src/control/win-native.ts')
s = p.read_text(encoding='utf-8')

old_imports = '''    [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);\n    [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int command);\n'''
new_imports = '''    [DllImport("user32.dll")] public static extern bool SetForegroundWindow(IntPtr hWnd);\n    [DllImport("user32.dll")] public static extern bool BringWindowToTop(IntPtr hWnd);\n    [DllImport("user32.dll")] public static extern IntPtr SetFocus(IntPtr hWnd);\n    [DllImport("user32.dll")] public static extern uint GetCurrentThreadId();\n    [DllImport("user32.dll")] public static extern bool AttachThreadInput(uint idAttach, uint idAttachTo, bool attach);\n    [DllImport("user32.dll")] public static extern bool ShowWindowAsync(IntPtr hWnd, int command);\n'''
if old_imports not in s:
    raise SystemExit('activation import marker missing')
s = s.replace(old_imports, new_imports, 1)

old_activate = '''    public static IntPtr Activate(string appName) {\n        var hWnd = FindWindow(appName);\n        if (hWnd == IntPtr.Zero) throw new InvalidOperationException("target app window not found");\n        if (GetForegroundWindow() == hWnd) return hWnd;\n        ShowWindowAsync(hWnd, SW_RESTORE);\n        if (!SetForegroundWindow(hWnd)) throw new InvalidOperationException("Windows refused to activate the target app window");\n        Thread.Sleep(75);\n        if (GetForegroundWindow() != hWnd) throw new InvalidOperationException("target app did not become foreground; synthetic input refused");\n        return hWnd;\n    }\n'''
new_activate = '''    static bool WaitForForeground(IntPtr hWnd, int timeoutMs) {\n        var sw = Stopwatch.StartNew();\n        do {\n            if (GetForegroundWindow() == hWnd) return true;\n            Thread.Sleep(25);\n        } while (sw.ElapsedMilliseconds < timeoutMs);\n        return GetForegroundWindow() == hWnd;\n    }\n\n    static void NudgeForegroundPermission() {\n        // Windows can reject SetForegroundWindow for a background helper even\n        // after the user has authorized control. A tiny Alt down/up is the\n        // standard foreground-lock nudge; it does not type text or target an\n        // arbitrary window and is used only after the exact allowlisted target\n        // has already been resolved.\n        var inputs = new INPUT[2];\n        inputs[0].type = INPUT_KEYBOARD; inputs[0].U.ki.wVk = 0x12;\n        inputs[1] = inputs[0]; inputs[1].U.ki.dwFlags = KEYEVENTF_KEYUP;\n        SendInput(2, inputs, Marshal.SizeOf(typeof(INPUT)));\n    }\n\n    public static IntPtr Activate(string appName) {\n        var hWnd = FindWindow(appName);\n        if (hWnd == IntPtr.Zero) throw new InvalidOperationException("target app window not found");\n        if (GetForegroundWindow() == hWnd) return hWnd;\n\n        ShowWindowAsync(hWnd, SW_RESTORE);\n\n        uint ignoredPid;\n        uint currentThread = GetCurrentThreadId();\n        IntPtr foregroundWindow = GetForegroundWindow();\n        uint foregroundThread = foregroundWindow == IntPtr.Zero ? 0 : GetWindowThreadProcessId(foregroundWindow, out ignoredPid);\n        uint targetThread = GetWindowThreadProcessId(hWnd, out ignoredPid);\n        bool attachedForeground = false;\n        bool attachedTarget = false;\n\n        try {\n            if (foregroundThread != 0 && foregroundThread != currentThread)\n                attachedForeground = AttachThreadInput(currentThread, foregroundThread, true);\n            if (targetThread != 0 && targetThread != currentThread && targetThread != foregroundThread)\n                attachedTarget = AttachThreadInput(currentThread, targetThread, true);\n\n            BringWindowToTop(hWnd);\n            SetForegroundWindow(hWnd);\n            SetFocus(hWnd);\n        } finally {\n            if (attachedTarget) AttachThreadInput(currentThread, targetThread, false);\n            if (attachedForeground) AttachThreadInput(currentThread, foregroundThread, false);\n        }\n\n        if (!WaitForForeground(hWnd, 350)) {\n            NudgeForegroundPermission();\n            ShowWindowAsync(hWnd, SW_RESTORE);\n            BringWindowToTop(hWnd);\n            SetForegroundWindow(hWnd);\n        }\n\n        if (!WaitForForeground(hWnd, 700))\n            throw new InvalidOperationException("target app did not become foreground; synthetic input refused");\n        return hWnd;\n    }\n'''
if old_activate not in s:
    raise SystemExit('Activate marker missing')
s = s.replace(old_activate, new_activate, 1)

p.write_text(s, encoding='utf-8')
